config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :patients do
    resources :appointments, shallow: true
  end
  resources :doctors do
      resources :appointments, shallow: true
  end
  resources :ballot_inititives
  resources :teams do
    resources :team_users, path: :users,  module: :teams
  end

  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :doctors
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if patient.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', patient, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if patient.persisted? %>
      <%= link_to "Cancel", patient, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", patients_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Edit Patient</h1>

<%= render 'form', patient: @patient %>

app/views/patients/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Patients</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_patient_path, class: 'btn btn-primary' do %>
    Add New Patient
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    
        <th>Name</th>
    

            
      </tr>
    </thead>

    <tbody>
      <% @patients.each do |patient| %>
        <%= content_tag :tr, id: dom_id(patient), class: dom_class(patient) do %>
          
            <td><%= link_to patient.name, patient %></td>
          

          
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form', patient: @patient %>

app/views/patients/show.html.erb
<div class="page-header">
  <%= link_to patients_path, class: 'btn btn-default' do %>
    All Patients
  <% end %>
  <%= link_to edit_patient_path(@patient), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show patient</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @patient.name %></dd>

</dl>