config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :patients do
    resources :appointments, shallow: true
  end
  resources :doctors do
      resources :appointments, shallow: true
  end
  resources :ballot_inititives
  resources :teams do
    resources :team_users, path: :users,  module: :teams
  end

  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :appointments
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doctor_params
      params.require(:doctor).permit(:name)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if doctor.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', doctor, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if doctor.persisted? %>
      <%= link_to "Cancel", doctor, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", doctors_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Edit Doctor</h1>

<%= render 'form', doctor: @doctor %>

app/views/doctors/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Doctors</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_doctor_path, class: 'btn btn-primary' do %>
    Add New Doctor
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    
        <th>Name</th>
    

            
      </tr>
    </thead>

    <tbody>
      <% @doctors.each do |doctor| %>
        <%= content_tag :tr, id: dom_id(doctor), class: dom_class(doctor) do %>
          
            <td><%= link_to doctor.name, doctor %></td>
          

          
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render 'form', doctor: @doctor %>

app/views/doctors/show.html.erb
<div class="page-header">
  <%= link_to doctors_path, class: 'btn btn-default' do %>
    All Doctors
  <% end %>
  <%= link_to edit_doctor_path(@doctor), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show doctor</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @doctor.name %></dd>

</dl>