config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :patients do
    resources :appointments, shallow: true
  end
  resources :doctors do
      resources :appointments, shallow: true
  end
  resources :ballot_inititives
  resources :teams do
    resources :team_users, path: :users,  module: :teams
  end

  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ballot_inititive.rb
class BallotInititive < ApplicationRecord
  belongs_to :team
end

app/controllers/ballot_inititives_controller.rb
class BallotInititivesController < ApplicationController
  before_action :set_ballot_inititive, only: [:show, :edit, :update, :destroy]

  # GET /ballot_inititives
  # GET /ballot_inititives.json
  def index
    @ballot_inititives = BallotInititive.all
  end

  # GET /ballot_inititives/1
  # GET /ballot_inititives/1.json
  def show
  end

  # GET /ballot_inititives/new
  def new
    @ballot_inititive = BallotInititive.new
  end

  # GET /ballot_inititives/1/edit
  def edit
  end

  # POST /ballot_inititives
  # POST /ballot_inititives.json
  def create
    @ballot_inititive = BallotInititive.new(ballot_inititive_params)

    respond_to do |format|
      if @ballot_inititive.save
        format.html { redirect_to @ballot_inititive, notice: 'Ballot inititive was successfully created.' }
        format.json { render :show, status: :created, location: @ballot_inititive }
      else
        format.html { render :new }
        format.json { render json: @ballot_inititive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ballot_inititives/1
  # PATCH/PUT /ballot_inititives/1.json
  def update
    respond_to do |format|
      if @ballot_inititive.update(ballot_inititive_params)
        format.html { redirect_to @ballot_inititive, notice: 'Ballot inititive was successfully updated.' }
        format.json { render :show, status: :ok, location: @ballot_inititive }
      else
        format.html { render :edit }
        format.json { render json: @ballot_inititive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ballot_inititives/1
  # DELETE /ballot_inititives/1.json
  def destroy
    @ballot_inititive.destroy
    respond_to do |format|
      format.html { redirect_to ballot_inititives_url, notice: 'Ballot inititive was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ballot_inititive
      @ballot_inititive = BallotInititive.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ballot_inititive_params
      params.require(:ballot_inititive).permit(:name, :team_id)
    end
end

app/helpers/ballot_inititives_helper.rb
module BallotInititivesHelper
end

app/views/ballot_inititives/_form.html.erb
<%= form_with(model: ballot_inititive, local: true) do |form| %>
  <% if ballot_inititive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ballot_inititive.errors.count, "error") %> prohibited this ballot_inititive from being saved:</h2>

      <ul>
      <% ballot_inititive.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :team_id %>
    <%= form.text_field :team_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if ballot_inititive.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', ballot_inititive, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if ballot_inititive.persisted? %>
      <%= link_to "Cancel", ballot_inititive, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", ballot_inititives_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/ballot_inititives/edit.html.erb
<h1>Edit Ballot_inititive</h1>

<%= render 'form', ballot_inititive: @ballot_inititive %>

app/views/ballot_inititives/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Ballot_inititives</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_ballot_inititive_path, class: 'btn btn-primary' do %>
    Add New Ballot inititive
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    
        <th>Name</th>
    

            <th>Team</th>
            
      </tr>
    </thead>

    <tbody>
      <% @ballot_inititives.each do |ballot_inititive| %>
        <%= content_tag :tr, id: dom_id(ballot_inititive), class: dom_class(ballot_inititive) do %>
          
            <td><%= link_to ballot_inititive.name, ballot_inititive %></td>
          

                      <td><%= ballot_inititive.team %></td>
          
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/ballot_inititives/new.html.erb
<h1>New ballot_inititive</h1>

<%= render 'form', ballot_inititive: @ballot_inititive %>

app/views/ballot_inititives/show.html.erb
<div class="page-header">
  <%= link_to ballot_inititives_path, class: 'btn btn-default' do %>
    All Ballot_inititives
  <% end %>
  <%= link_to edit_ballot_inititive_path(@ballot_inititive), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show ballot_inititive</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @ballot_inititive.name %></dd>

  <dt>Team:</dt>
  <dd><%= @ballot_inititive.team %></dd>

</dl>